# Generated by Django 2.1.1 on 2019-05-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190521_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='correct_value',
            field=models.IntegerField(null=True),
        ),
    ]
